language: node_js
dist: focal
before_install:
    - sudo apt update && sudo apt -y install libbpfcc-dev
cache:
    directories:
        - ~/.npm
notifications:
    email: false
node_js:
    - 12
script:
    - true # npm run test && npm run build

# jobs:
#     include:
#         - stage: coverage
#           name: Coverage
#           node_js: 12
#           script: npm run test; npm run report-coverage
